import Header from '@/components/server/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/server/Footer'
import { Slide, ToastContainer } from 'react-toastify'
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Certificate Generation',
  description: 'Generated by Certificate Generation',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className='min-h-screen'>
          {children}
        </main>
        <ToastContainer position="top-right"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={true}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          transition={Slide}
          // progressStyle={''}
          className={"toast_container"}
          theme={'colored'} />
        <Footer />
      </body>
    </html>
  )
}
